version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: edu_system
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "5432:5432"

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/edu_system
      SECRET_KEY: django-insecure-your-secret-key-here

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data: