@startuml
title Система учета успеваемости - Диаграмма активности

start

:Вход в приложение;

if (Проверка данных) then (Неверно)
  :Отказ в доступе;
  stop
else (Верно)
  if (Роль пользователя?) then (Студент)
    partition Студент {
      :Доступ к своим данным;
      if (Выбор действия) then (Оценки)
        :Просмотр оценок;
      elseif (Комментарии)
        :Просмотр комментариев;
      elseif (Предметы)
        :Просмотр предметов;
      endif
      :Завершение сеанса;
    }
  else (Учитель)
    partition Учитель {
      :Выбор ученика;
      if (Действие с учеником) then (Выставить оценку)
        :Выставление оценки по ФГОС;
        :Сохранить в БД;
        :Обновление средних баллов;
        :Завершение сеанса;
      elseif (Написать комментарий)
        :Написание комментария;
        :Сохранить в БД;
        :Обновление средних баллов;
        :Завершение сеанса;
      elseif (Просмотреть данные)
        if (Что просмотреть?) then (Оценки)
          :Просмотр оценок;
        elseif (Комментарии)
          :Просмотр комментариев;
        elseif (Предметы)
          :Просмотр предметов;
        endif
        :Завершение сеанса;
      endif
    }
  endif
endif

stop
@enduml