@startuml
left to right direction
skinparam usecase {
    BackgroundColor LightBlue
    BorderColor DarkGray
}

actor "Студент" as Student

rectangle "Учебный портал" {
  Student --> (Открыть раздел "Успеваемость")
  (Открыть раздел "Успеваемость") --> (Просмотр списка предметов)
  (Просмотр списка предметов) --> (Выбор предмета)
  (Выбор предмета) --> (Просмотр оценок)
  (Выбор предмета) --> (Просмотр комментариев)
  (Выбор предмета) --> (Просмотр среднего балла)
  
  (Просмотр списка предметов) <.. (Нет данных) : extend
}

note right of (Нет данных)
  Отображается сообщение
  "Нет данных"
end note

@enduml